var data = [
  {
    "id":1,
    "pid":null,
    "key":1,
    "title":"1-1111",
    "children":[
      {
        "id":2,
        "pid":1,
        "key":2,
        "title":"2-1111",
        "children":[
          {
            "id":4,
            "pid":2,
            "key":4,
            "title":"8-1111",
            "children":[]
          },
          {
            "id":5,
            "pid":2,
            "key":5,
            "title":"9-1111",
            "children":[
              {
                "id":7,
                "pid":5,
                "key":7,
                "title":"5-1111",
                "children":[]
              },
              {
                "id":8,
                "pid":5,
                "key":8,
                "title":"8-1111",
                "children":[]
              }
            ]
          },
          {
            "id":6,
            "pid":2,
            "key":6,
            "title":"10-1111",
            "children":[]
          }
        ]
      },
      {
        "id":3,
        "pid":1,
        "key":3,
        "title":"9-1111",
        "children":[]
      }
    ]
  }
]